#!/bin/bash
if [ -z "$XDG_CONFIG_HOME" ]; then
    XDG_CONFIG_HOME="$HOME/.config"
fi

if  [ ! -f "$XDG_CONFIG_HOME/touhoudoom/gzdoom.ini" ]; then
    if [ ! -d "$XDG_CONFIG_HOME/touhoudoom" ]; then
        mkdir "$XDG_CONFIG_HOME/touhoudoom"
    fi
    cp "/usr/share/games/doom/gzdoom-touhou.ini" "$XDG_CONFIG_HOME/touhoudoom/gzdoom.ini"
fi

if  [ -f "/usr/share/games/doom/DOOM2.WAD" ] || [ -f "/usr/share/doom/DOOM2.WAD" ]; then
    iwad="DOOM2.WAD"
else
    iwad="freedoom2.wad"
fi

gzdoom -config "$XDG_CONFIG_HOME/touhoudoom/gzdoom.ini" -iwad $iwad -file touhoudoom.pk3
