# 本脚本能让该脚本在Github Active上面执行
name: Upload Health Situation

on:
  # 可以人工执行
  workflow_dispatch:
  # 按时间执行 这里说是伦敦的00:00执行，也就是北京时间8:00
  schedule:
     - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyppeteer
    - name: Checkout
      run: |
        python reportNcov-outschool.py
